### ISSUE TITLE
I have a leap project like this and use leaptrainer too, but it's doesn't work?

### ISSUE THREAD

**Issue by alexxxcs1** [AdrianLoer/LeapStuff#1]
like leaptrainer tutorial say , I train gesture in [web leaptrainer ](https://rawgit.com/roboleary/LeapTrainer.js/master/trainer-ui.html)

I save the gesture JSON to local ,and in my project i  paste JSON in my javascript code

and i import JSON like this:

 `trainer.fromJSON(JSON.stringify(down));`

but i  not work ,can not recognized gesture

and in gesture-unknown it can see import gesture scuess : 

``
trainer.on('gesture-unknown', function(allHits) {
        console.log(allHits);
 });
``

it print in console : 

`
{DOWN: 0, DOWN2: 0, LEFT: 0, LEFT2: 0, RIGHT: 0, …}
`

**Comment by AdrianLoer** [comment]
sorry to disappoint but haven't done anything with leap in years. No idea
